### ISSUE TITLE
出不来图

### ISSUE THREAD

**Issue by Agnes4m** [KimigaiiWuyi/SayuStock#1]
![image](https://github.com/user-attachments/assets/058dd9f2-b8f1-47bd-9c96-b86c2fe60d7b)

**Comment by KimigaiiWuyi** [comment]
playwright install了吗

**Comment by Agnes4m** [comment]
用了，还是没有

**Comment by Agnes4m** [comment]
![3a5628db8fe23667289226123a0c40b7](https://github.com/user-attachments/assets/6a0a9cba-a81e-46c1-aba3-e05614654aa0)
